### ISSUE TITLE
打开首页错误

### ISSUE THREAD

**Issue by sunmaxwell666** [netcccyun/wxredirect#1]
Warning: require(/www/wwwroot/xxx.com/public/../vendor/autoload.php): failed to open stream: No such file or directory in /www/wwwroot/xxx.com/public/index.php on line 15

Fatal error: require(): Failed opening required '/www/wwwroot/xxx.com/public/../vendor/autoload.php' (include_path='.:') in /www/wwwroot/xxx.com/public/index.php on line 15

**Comment by netcccyun** [comment]
下载错了，应该下载release里面的压缩包
